### ISSUE TITLE
Composer Requirements Laravel 9.30.0 

### ISSUE THREAD

**Issue by johnnywo** [njoguamos/laravel-zoho-oauth#13]
Just wanted to let you know, wanted to try your package:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires njoguamos/laravel-zoho-oauth ^0.2.2 -> satisfiable by njoguamos/laravel-zoho-oauth[v0.2.2].
    - njoguamos/laravel-zoho-oauth v0.2.2 requires illuminate/database ^8.0 -> found illuminate/database[v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
```

Thank you

**Comment by njoguamos** [comment]
@johnnywo What is your Laravel version?

**Comment by johnnywo** [comment]
Hi @njoguamos! - its 9.30.0

**Comment by njoguamos** [comment]
Laravel 9.* support has been [added](https://github.com/njoguamos/laravel-zoho-oauth/pull/14). Try installing latest [version (v0.3.0)](https://github.com/njoguamos/laravel-zoho-oauth/releases/tag/v0.3.0)

**Comment by johnnywo** [comment]
@njoguamos Thanks a lot! Looks good now!

**Comment by njoguamos** [comment]
@johnnywo Great. All the best in your project.
