### ISSUE TITLE
Authorization token method/function failing

### ISSUE THREAD

**Issue by johnmcguinness-buroserv** [njoguamos/laravel-zoho-oauth#16]
Hi Guys,

The method/function: 

`$latestToken = Zouath::latest();
$token = $latestToken->authorization_token;`

from your Welcome Github page:
[https://njoguamos.github.io/laravel-zoho-oauth/](url)

is returning the error:
Class "App\Http\Controllers\Api\Auth\Zouath" not found.

I also get an intelephense error (1009):
Undefined type 'App\Http\Controllers\Api\Auth\Zouath' intelephense(1009).

I can't trace the class back in your code to debug my implementation.
The database has the refresh and access tokens generated by Zoho stored correctly.

I thought it might be a typo ie: Zouath should be Zoauth, but that also returns:

Undefined type 'App\Http\Controllers\Api\Auth\Zoauth'.intelephense(1009) and
Class "App\Http\Controllers\Api\Auth\Zoauth" not found.

Dev Environment
Server: Localhost on Laragon
Apache: 2.4
PHP: 8.1.2
MySQL: 5.7
Laravel Framework 9.42.2
"njoguamos/laravel-zoho-oauth": "^0.4.0"

Here is a copy of the Controller I'm trying to implement this in:
```
namespace App\Http\Controllers\Api\Auth;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Http;
use Sammyjo20\Saloon\Http\Auth\AccessTokenAuthenticator;

class QntrlController extends Controller

{
    public function index()

    {
        $accessToken = Zoauth::latest();// $this->getAccessToken();

        $cards = null;

        $response = Http::withHeaders(['Authorization' => 'Zoho-oauthtoken '.$accessToken, 'Content-Type' => 'application/json'])->get('https://orchestly.zoho.com.au/blueprint/api/buroservaustralia/job');

        if ($response->successful()) {

            $cards = json_decode($response, true);

            $cards = $cards['job_list'];

        }

        return $accessToken;

        // return view('api.auth.qntrl.index', ['cards' => $cards]);

    }" not found
```
I'm just returning the access token as a dump to see the results.
Please advise. You can contact me directly on john.mcguinness (at) buroserv.com.au
Thanks!

**Comment by njoguamos** [comment]
Apologies for the typo.

```php

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Http;
use Sammyjo20\Saloon\Http\Auth\AccessTokenAuthenticator;

// Add this namespace
use Njoguamos\LaravelZohoOauth\Models\ZohoOauth;

```

**Comment by njoguamos** [comment]
You are correct there are typos in the Documentation. I will fix it.

Update the code as follows and let me know how it goes.

```php
namespace App\Http\Controllers\Api\Auth;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Http;
use Sammyjo20\Saloon\Http\Auth\AccessTokenAuthenticator;

// Remember to import the model
use Njoguamos\LaravelZohoOauth\Models\ZohoOauth;

class QntrlController extends Controller

{
    public function index()

    {
        // Update this line. IT should return the full Zoho token
        $accessToken = ZohoOauth::latest()?->auth_token; 
       // "Zoho-oauthtoken 1000.27cb28ac001d4f1b610f06c414fc5d5a.8fa8f34f61e4c2cc9c466e8aaccba395"
      

        $cards = null;

        $response = Http::withHeaders([
             'Authorization' => $accessToken, 
             'Content-Type' => 'application/json'
         ])->get('https://orchestly.zoho.com.au/blueprint/api/buroservaustralia/job');

        if ($response->successful()) {

            $cards = json_decode($response, true);

            $cards = $cards['job_list'];

        }

        return $accessToken;

        // return view('api.auth.qntrl.index', ['cards' => $cards]);

    }
}
```

**Comment by johnmcguinness-buroserv** [comment]
Hi Njogu,

Thanks for the response.
So far so good.
New issue now is:
**_Property [auth_token] does not exist on the Eloquent builder instance._**

I ran  php artisan zoauth:refresh
and got the following message:
Successfully saved authorization codes to the database.

I also checked the database and the latest access_token was there.
Here is a view of the database:

![zoho_oauth-table](https://user-images.githubusercontent.com/112837996/207181269-b3ed9a3d-1cdd-4e77-92d3-ee35a9d39cd0.png)

Not sure what I'm missing.
My code:
```
class QntrlController extends Controller
{
    public function index() 
    {
        $accessToken = ZohoOauth::latest()?->auth_token;
        // "Zoho-oauthtoken 1000.27cb28ac001d4f1b610f06c414fc5d5a.8fa8f34f61e4c2cc9c466e8aaccba395"

        $cards = null;
        $response = Http::withHeaders([
            'Authorization' => $accessToken, 
            'Content-Type' => 'application/json'
            ])->get('https://orchestly.zoho.com.au/blueprint/api/buroservaustralia/job');
        if ($response->successful()) {

            $cards = json_decode($response, true);

            $cards = $cards['job_list'];

        }
        
        return view('api.auth.qntrl.index', ['cards' => $cards]);
    }
```

Also, on a side note.
I think it's a typo on the doc's page. You've got **$token =** and then use **$accessToken** in the withHeaders().
```
$token = ZohoOauth::latest()?->auth_token;
     // "Zoho-oauthtoken 1000.27cb28ac001d4f1b610f06c414fc5d5a.8fa8f34f61e4c2cc9c466e8aaccba395"

      $response = Http::withHeaders(['Authorization' => $accessToken])->get(//zoho url);
```
Thanks for the support!

**Comment by njoguamos** [comment]
Thank you for testing. I have fixed the typo in the documentation.


The `auth_token` is a computed attribute, refer to this code
https://github.com/njoguamos/laravel-zoho-oauth/blob/a7dff0796b3c8360de5bca867c23271b1bd14b59/src/Models/ZohoOauth.php#L23-L28

Let me know if the problem still persists.
