### ISSUE TITLE
Eloquent error when calling for the access_token

### ISSUE THREAD

**Issue by johnmcguinness-buroserv** [njoguamos/laravel-zoho-oauth#17]
Hi njoguamos,

I've checked out all of the previous correction/suggestions in the last issue.
I'm still getting the Eloquent Builder error as follow:
`Property [auth_token] does not exist on the Eloquent builder instance.`

I'm trying to get the access_token using: 
`$accessToken = ZohoOauth::latest()?->auth_token;`

My Controller code to the index() function:

```
namespace App\Http\Controllers\Api\Auth;

use Sammyjo20\Saloon\Http\Auth\AccessTokenAuthenticator;
use App\Models\Qntrl;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use Illuminate\Support\Facades\Http;

use Njoguamos\LaravelZohoOauth\Models\ZohoOauth;

class QntrlController extends Controller
{
    public function index() 
    {
        $accessToken = ZohoOauth::latest()?->auth_token;
        // "Zoho-oauthtoken 1000.27cb28ac001d4f1b610f06c414fc5d5a.8fa8f34f61e4c2cc9c466e8aaccba395"
        
        // $accessToken = $this->getAccessToken();

        $cards = null;
        $response = Http::withHeaders([
            'Authorization' => $accessToken
            ])->get('https://orchestly.zoho.com.au/blueprint/api/buroservaustralia/job');
        if ($response->successful()) {

            $cards = json_decode($response, true);

            $cards = $cards['job_list'];

        }
        
        return view('api.auth.qntrl.index', ['cards' => $cards]);
    }
```
I can't see the cause of the Eloquent error.

Please let me know what you think.
Thanks!

**Comment by njoguamos** [comment]
I will have a look at it and revert.

**Comment by johnmcguinness-buroserv** [comment]
Thanks!
Let me know if there's any additional info or code that you require.
R
John

**Comment by johnmcguinness-buroserv** [comment]
Hi Njoguamos,

I got the $token = ZohoOauth::latest()?->auth_token; working as the following:

```
$token = ZohoOauth::latest()->first();
$accessToken = 'Zoho-oauthtoken ' . $token->access_token;
```
I'm on a Windows  box using Laragon as the dev environment.

**Comment by njoguamos** [comment]
Thank you for your feedback.

I will update the documentation. 


`latest()` is an ordering parameter and it doesn't indeed fetch the data.

**Comment by njoguamos** [comment]
I have updated the docs.
