### ISSUE TITLE
Problems with "php artisan zoauth:init"

### ISSUE THREAD

**Issue by github-grabaz** [njoguamos/laravel-zoho-oauth#18]
The first time running received the error: **Class "http\Exception\RuntimeException" not found**

Fixed by directly editing ZohoCredentials.php and the following code:

    public function makeRequestToZohoAccounts(array $body)
    {
        $response = Http::asForm()->post($this->getEndPointUrl(), $body);

        if (!$response->successful()) {
            // commented the following out since Class not found
            // throw new RuntimeException('Unexpected error occurred. Please try again later.');
            // using laravel method instead
            $response->throw();
        }

        return $response->json();
    }

This revealed that a 404 error was being returned.

Diagnosed this problem to an unneeded "/" in ZohoCredentials.php.  Specifically, the following code:
    const END_POINT = '/oauth/v2/token';

Needed to be changed to:
    const END_POINT = 'oauth/v2/token';

**Comment by njoguamos** [comment]
Thank you.

I will look at it and revert ASAP.

**Comment by njoguamos** [comment]
@github-grabaz I have looked at it. Check if your base URL has a trailing slash and remove it.

https://github.com/njoguamos/laravel-zoho-oauth/blob/a7dff0796b3c8360de5bca867c23271b1bd14b59/config/zoho-oauth.php#L20-L25

**Comment by github-grabaz** [comment]
The class not found problem is the real issue.

The "/" issues was because I included a "/" in my .env settings for the following:

BASE_OAUTH_URL=https://accounts.zoho.com/

So maybe some clearer directions for the .env settings.

**Comment by njoguamos** [comment]
I will update the runtime exception.

**Comment by github-grabaz** [comment]
FYI - The instructions at https://njoguamos.github.io/laravel-zoho-oauth/instructions show the trailing "/" in the BASE_OAUTH_URL config.

**Comment by github-grabaz** [comment]
Thanks for your help!

**Comment by njoguamos** [comment]
> FYI - The instructions at https://njoguamos.github.io/laravel-zoho-oauth/instructions show the trailing "/" in the BASE_OAUTH_URL config.

Thank you for identifying the typo. I will fix it.

**Comment by github-grabaz** [comment]
Ok - closing
